{"name": "test_log_in_failed", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'ERROR: Incorrect username or password.' in 'ERROR: Too many failed login attempts. Please try again in 9 minutes.'\n +  where 'ERROR: Too many failed login attempts. Please try again in 9 minutes.' = <bound method MyAccountPage.get_error_msg of <page_object_patern.pages.my_account_page.MyAccountPage object at 0x000001C1EB3F9FD0>>()\n +    where <bound method MyAccountPage.get_error_msg of <page_object_patern.pages.my_account_page.MyAccountPage object at 0x000001C1EB3F9FD0>> = <page_object_patern.pages.my_account_page.MyAccountPage object at 0x000001C1EB3F9FD0>.get_error_msg", "trace": "self = <page_object_patern.tests.login_test.TestLogIn object at 0x000001C1EA93C050>\n\n    def test_log_in_failed(self):\n        my_account_page = MyAccountPage(self.driver)\n        my_account_page.open_page()\n        my_account_page.log_in(\"sialalala1@gmail.coml\", \"Tester12345!@#$%\")\n    \n>       assert \"ERROR: Incorrect username or password.\" in my_account_page.get_error_msg()\nE       AssertionError: assert 'ERROR: Incorrect username or password.' in 'ERROR: Too many failed login attempts. Please try again in 9 minutes.'\nE        +  where 'ERROR: Too many failed login attempts. Please try again in 9 minutes.' = <bound method MyAccountPage.get_error_msg of <page_object_patern.pages.my_account_page.MyAccountPage object at 0x000001C1EB3F9FD0>>()\nE        +    where <bound method MyAccountPage.get_error_msg of <page_object_patern.pages.my_account_page.MyAccountPage object at 0x000001C1EB3F9FD0>> = <page_object_patern.pages.my_account_page.MyAccountPage object at 0x000001C1EB3F9FD0>.get_error_msg\n\npage_object_patern\\tests\\login_test.py:21: AssertionError"}, "attachments": [{"name": "stdout", "source": "0aef3ad2-e2c7-40b0-9dfa-baacd36b7354-attachment.txt", "type": "text/plain"}], "start": 1683796674067, "stop": 1683796675861, "uuid": "e36b9222-1579-4df6-9cfe-7b0495551fbc", "historyId": "f4b1f1a29402a58bee951e2d821863e0", "testCaseId": "f4b1f1a29402a58bee951e2d821863e0", "fullName": "page_object_patern.tests.login_test.TestLogIn#test_log_in_failed", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "page_object_patern.tests"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLogIn"}, {"name": "host", "value": "LaptopAsia"}, {"name": "thread", "value": "15620-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "page_object_patern.tests.login_test"}]}